services:
  - docker:dind

build-only:
  stage: build
  image: docker:latest
  before_script:
    - apk add --no-cache bash
  script:
    - ./backend/ci/build.sh
  except:
    - tags

build-delivery:
  stage: build
  image: riccardocampisano/public:docker_buildx_1.0.0
  script:
    - ./backend/ci/delivery.sh
  only:
    - tags
