version: '3.7'

services:

  reverse-proxy:
    image: 'traefik:v2.9.6'
    command: --providers.docker
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - 'traefik.http.middlewares.gzip.compress=true'
      - 'traefik.http.middlewares.gzip.compress.excludedcontenttypes=image/png, image/jpeg, font/woff2'

  frontend:
    image: 'plone/plone-frontend:16.5.0'
    environment:
      - 'RAZZLE_INTERNAL_API_PATH=http://backend:8080/Plone'
    ports:
      - '3000:3000'
    depends_on:
      - backend
    labels:
      # from https://training.plone.org/effective-volto/deployment/docker.html?highlight=traefik
      - 'traefik.enable=true'

      - 'traefik.http.services.plone-frontend-srv.loadbalancer.server.port=3000'
      - 'traefik.http.services.plone-frontend-srv.loadBalancer.sticky.cookie=true'
      - 'traefik.http.services.plone-frontend-srv.loadbalancer.sticky.cookie.samesite=strict'
      - 'traefik.http.services.plone-frontend-srv.loadBalancer.sticky.cookie.name=plone-frontend-sticky-cookie'

      - 'traefik.http.routers.plone-frontend-http-rl.rule=Host(`localhost`) && ( ! PathPrefix(`/++api++`) )'
      - 'traefik.http.routers.plone-frontend-http-rl.service=plone-frontend-srv'
      - 'traefik.http.routers.plone-frontend-http-rl.middlewares=gzip'

  backend:
    image: 'plone/plone-backend:6.0.0.2'
    environment:
      - 'SITE=Plone'
      - 'PROFILES=plone.volto:default-homepage'
    ports:
      - '8080:8080'
    labels:
      # from https://training.plone.org/effective-volto/deployment/docker.html?highlight=traefik
      - 'traefik.enable=true'

      - 'traefik.http.services.plone-backend-srv.loadbalancer.server.port=8080'
      - 'traefik.http.services.plone-backend-srv.loadBalancer.sticky.cookie=true'
      - 'traefik.http.services.plone-backend-srv.loadbalancer.sticky.cookie.samesite=strict'
      - 'traefik.http.services.plone-backend-srv.loadBalancer.sticky.cookie.name=plone-backend-sticky-cookie'

      - 'traefik.http.middlewares.plone-backend-rewrite-mdw.replacepathregex.regex=^/\+\+api\+\+($$|/.*)'
      - 'traefik.http.middlewares.plone-backend-rewrite-mdw.replacepathregex.replacement=/VirtualHostBase/http/localhost/Plone/++api++/VirtualHostRoot/$$1'

      - 'traefik.http.routers.plone-backend-http-rl.rule=Host(`localhost`) && PathPrefix(`/++api++`)'
      - 'traefik.http.routers.plone-backend-http-rl.service=plone-backend-srv'
      - 'traefik.http.routers.plone-backend-http-rl.middlewares=gzip,plone-backend-rewrite-mdw'
