version: '3.7'

networks:
  edge-net:
    external: true

secrets:
  plone_RELSTORAGE_ORA_USR_v1:
    external: true
  plone_RELSTORAGE_ORA_PWD_v1:
    external: true
  plone_RELSTORAGE_DSN_v1:
    external: true
  plone_TNS_ADMIN_FILEDATA_v1:
    external: true

services:

  reverse-proxy:
    image: 'traefik:v2.9.6'
    networks:
      - edge-net
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    command:
      - '--log.level=INFO'
      - '--accesslog'
      - '--providers.docker=true'
      - '--providers.docker.watch=true'
      - '--providers.docker.swarmMode=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=edge-net'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--entryPoints.web.address=:80'
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
      labels:
        # enable traefik, because we disabled expose a service by default
        - 'traefik.enable=true'

        # dummy service required by swarm but not used
        - 'traefik.http.services.traefik-srv.loadbalancer.server.port=888'

        # define middlewares
        - 'traefik.http.middlewares.gzip.compress=true'
        - 'traefik.http.middlewares.gzip.compress.excludedcontenttypes=image/png, image/jpeg, font/woff2'

  frontend:
    image: 'plone/plone-frontend:16.5.0'
    networks:
      - edge-net
    environment:
      - 'RAZZLE_INTERNAL_API_PATH=http://backend:8080/Plone'
    deploy:
      replicas: 1
      labels:
        # from https://training.plone.org/effective-volto/deployment/docker.html?highlight=traefik
        - 'traefik.enable=true'

        - 'traefik.http.services.plone-frontend-srv.loadbalancer.server.port=3000'
        - 'traefik.http.services.plone-frontend-srv.loadBalancer.sticky.cookie=true'
        - 'traefik.http.services.plone-frontend-srv.loadbalancer.sticky.cookie.samesite=strict'
        - 'traefik.http.services.plone-frontend-srv.loadBalancer.sticky.cookie.name=plone-frontend-sticky-cookie'

        - 'traefik.http.routers.plone-frontend-http-rl.rule=Host(`localhost`) && ( ! PathPrefix(`/++api++`) )'
        - 'traefik.http.routers.plone-frontend-http-rl.entrypoints=web'
        - 'traefik.http.routers.plone-frontend-http-rl.service=plone-frontend-srv'
        - 'traefik.http.routers.plone-frontend-http-rl.middlewares=gzip'

  backend:
    image: plone-backend:local
    networks:
      - edge-net
    # environment:
      # optionals env vars for Site first time creation
      # - 'SITE=Plone'
      # - 'PROFILES=plone.volto:default-homepage'
    secrets:
      - source: plone_RELSTORAGE_ORA_USR_v1
        target: RELSTORAGE_ORA_USR
      - source: plone_RELSTORAGE_ORA_PWD_v1
        target: RELSTORAGE_ORA_PWD
      - source: plone_RELSTORAGE_DSN_v1
        target: RELSTORAGE_DSN
      - source: plone_TNS_ADMIN_FILEDATA_v1
        target: TNS_ADMIN_FILEDATA
    deploy:
      replicas: 1
      labels:
        # from https://training.plone.org/effective-volto/deployment/docker.html?highlight=traefik
        - 'traefik.enable=true'

        - 'traefik.http.services.plone-backend-srv.loadbalancer.server.port=8080'
        - 'traefik.http.services.plone-backend-srv.loadBalancer.sticky.cookie=true'
        - 'traefik.http.services.plone-backend-srv.loadbalancer.sticky.cookie.samesite=strict'
        - 'traefik.http.services.plone-backend-srv.loadBalancer.sticky.cookie.name=plone-backend-sticky-cookie'

        - 'traefik.http.middlewares.plone-backend-rewrite-mdw.replacepathregex.regex=^/\+\+api\+\+($$|/.*)'
        - 'traefik.http.middlewares.plone-backend-rewrite-mdw.replacepathregex.replacement=/VirtualHostBase/http/localhost/Plone/++api++/VirtualHostRoot/$$1'

        - 'traefik.http.routers.plone-backend-http-rl.rule=Host(`localhost`) && PathPrefix(`/++api++`)'
        - 'traefik.http.routers.plone-backend-http-rl.entrypoints=web'
        - 'traefik.http.routers.plone-backend-http-rl.service=plone-backend-srv'
        - 'traefik.http.routers.plone-backend-http-rl.middlewares=gzip,plone-backend-rewrite-mdw'
